version: '3'
services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend-1
      - backend-2

  backend-1:
    build: ./backend
    expose:
      - "5000"
    environment:
      - FLASK_ENV=development

  backend-2:
    build: ./backend
    expose:
      - "5000"
    environment:
      - FLASK_ENV=development

  database:
    image: mysql/mysql-server:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123123123
      MYSQL_DATABASE: vd_ecommerce
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: 123123123
    ports:
      - "8080:80"
    depends_on:
      - database

volumes:
  db_data:
